### ISSUE TITLE
Readme Ergänzung

### ISSUE THREAD

**Issue by shyim** [rofthedeep/SubscriberTest#1]
Das Problem scheint mit https://github.com/shopware/shopware/pull/1376 gelöst zu sein.
Ich schau mir das die Tage mal genauer an und schaue ob wir das schnell behoben kriegen :wink: 

Vielleicht könnte man das noch in der readme erwähnen

**Comment by rofthedeep** [comment]
Ahh, sehr gut :) Hab mich auf das Ticket subscribed - dann bekomm ichs mit wenn die Änderung drinnen ist ...
Danke dir für den Hinweis!
